// flow-typed signature: 4708d4729cdbb5de7328e7fa249370ce
// flow-typed version: <<STUB>>/mobx_v3.2.2/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mobx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mobx' {
  declare module.exports: any;
}
