
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.8.1
      
    dependencies:
      override:
        - yarn
      cache_directories:
        - ~/.cache/yarn

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install
      - run: yarn lint:js
      - run: yarn lint:ts
      - run: yarn test
      - run: yarn type-check
test:
  override:
    - echo "done"



