
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn install
      - run: yarn lint:js
      - run: yarn lint:ts
      - run: yarn test
      - run: yarn type-check
  android:
    working_directory: ~/repo/android
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - checkout:
          path: ~/repo
      - attach_workspace:
          at: ~/repo
      - run: pwd
      - run: cd ~/repo/android
      - run: ./gradlew assembleRelease
        environment:
          TERM: dumb
      
workflows:
  version: 2
  node:
    jobs:
      - build
      - android:
          requires:
            - build
      



